#-------- DAY 64 "try-except" --------
print("Lesson 64: Try-Except")
try:
    print(name) #Will rais an error!!
except:
    print('An exception occurred!!')

# try:
#     print(name) #Will rais an error!!
# except NameError:
#     print('Variable name is not defined')
# except:
#     print('Something else went wrong')

# try:
#     print('Hello World')
# except:
#     print('Something went wrong')
# else:
#     print('Nothing went wrong')

# try:
#     print('Hello World')
# except:
#     print('Something went wrong')
# finally:
#     print("The 'try except' is finished")
